<?php

/**
 * @file
 * Ubercart Payment method for epay.kkb.kz
 */

// Define key storage direcroty path and keys filenames
define('UC_EPAY_KKB_CERT_DIR', $_SERVER['DOCUMENT_ROOT'] . base_path() . file_directory_path() . '/uc_epay_kkb');
define('UC_EPAY_KKB_BANK_CERT_FILENAME', 'kkbca.pem');
define('UC_EPAY_KKB_MERCH_CERT_FILENAME', 'merch.pem');

// Define default test and production URLs
define('UC_EPAY_KKB_TEST_GATEWAY_URL', 'https://3dsecure.kkb.kz/jsp/process/logon.jsp');
define('UC_EPAY_KKB_PROD_GATEWAY_URL', 'https://epay.kkb.kz/jsp/process/logon.jsp');


/**
 * Implementation of hook_payment_method().
 *
 * Exposes epay.kkb.kz to Ubercart.
 */
function uc_epay_kkb_payment_method() {
  $methods[] = array(
    'id' => 'epay_kkb',
    'name' => t('Credit card (ePay.kkb.kz)'),
    'title' => t('Credit card (ePay)'),
    'description' => t('Redirect to ePay.kkb.kz to pay by credit card.'),
    'callback' => 'uc_epay_kkb_payment_method_callback',
    'weight' => 1,
    'checkout' => TRUE,
    'no_gateway' => TRUE,
  );
  return $methods;
}

/**
 * Implements hook_form_alter().
 */
function uc_epay_kkb_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'uc_cart_checkout_review_form' && ($order_id = intval($_SESSION['cart_order'])) > 0) {
    $order = uc_order_load($order_id);

    if ($order->payment_method == 'epay_kkb') {
      unset($form['submit']);
      $form['#prefix'] = '<table id="epay-kkb-review-table"><tr><td>';
      $form['#suffix'] = '</td><td>'. drupal_get_form('uc_epay_kkb_form', $order) .'</td></tr></table>';
    }
  }
}

/**
 * Add ePay.kkb.kz settings to the payment method settings form.
 *
 * @see uc_epay_kkb_payment_method()
 */
function uc_epay_kkb_payment_method_callback($op, &$arg1) {
  switch ($op) {
    case 'settings':
      // Check keys
      uc_epay_kkb_check_cert_files();

      $form['api_url']['uc_epay_kkb_gateway_url'] = array(
        '#type' => 'textfield',
        '#title' => t('Gateway URL'),
        '#default_value' => variable_get('uc_epay_kkb_gateway_url', UC_EPAY_KKB_PROD_GATEWAY_URL),
        '#required' => TRUE,
      );

      $form['merchant'] = array(
        '#type' => 'fieldset',
        '#title' => t('Merchant Information'),
      );
      $form['merchant']['uc_epay_kkb_merchant_id'] = array(
        '#type' => 'textfield',
        '#title' => t('Merchant ID'),
        '#default_value' => variable_get('uc_epay_kkb_merchant_id', ''),
        '#required' => TRUE,
      );
      $form['merchant']['uc_epay_kkb_merchant_name'] = array(
        '#type' => 'textfield',
        '#title' => t('Shop/merchant name'),
        '#default_value' => variable_get('uc_epay_kkb_merchant_name', ''),
        '#required' => TRUE,
      );
      $form['merchant']['uc_epay_kkb_merchant_certificate_id'] = array(
        '#type' => 'textfield',
        '#title' => t('Certificate serial number'),
        '#default_value' => variable_get('uc_epay_kkb_merchant_certificate_id', ''),
        '#required' => TRUE,
      );

      $form['keys'] = array(
        '#type' => 'fieldset',
        '#title' => t('Keys'),
      );
      $form['keys']['uc_epay_kkb_private_key_pass'] = array(
        '#type' => 'textfield',
        '#title' => t('Merchant private key password'),
        '#default_value' => variable_get('uc_epay_kkb_private_key_pass', ''),
        '#required' => TRUE,
      );

      return $form;
  }
}

/**
 * Form to build the submission to epay.kkb.kz.
 */
function uc_epay_kkb_form($form_state, $order) {
  $form['#action'] = variable_get('uc_epay_kkb_gateway_url', UC_EPAY_KKB_PROD_GATEWAY_URL);
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit Order'),
  );
  return $form;
}


/*******************************************************************************
 * Module and Helper Functions
 ******************************************************************************/

/**
 * Check that a web accessible directory is exist and has been properly secured,
 * othewise attempt to secure it.
 *
 * Code from backup_mirgate module.
 */
function uc_epay_kkb_check_web_dir($directory) {
  // Check directory is existed
  if (!file_check_directory($directory, FILE_CREATE_DIRECTORY)) {
    $message = t("uc_epay_kkb was unable to create directory %directory. Please, create it by hand.",
                 array('%directory' => $directory));
    drupal_set_message($message, 'error');
    return FALSE;
  }
  // Check for a htaccess file which adequately protects the files.
  $htaccess_lines = "order allow,deny\ndeny from all\n";
  if (!is_file($directory .'/.htaccess') || !is_readable($directory .'/.htaccess') || strpos(file_get_contents($directory .'/.htaccess'), $htaccess_lines) === FALSE) {
    // Attempt to protect files from public access using htaccess.
    if (($fp = @fopen($directory .'/.htaccess', 'w')) && @fputs($fp, $htaccess_lines)) {
      fclose($fp);
      chmod($directory .'/.htaccess', 0664);
    }
    // Unable to create htaccess... warn the user.
    else {
      $message = "Security warning: Couldn't modify .htaccess file. Please create a .htaccess file in your %directory directory which contains the following lines: <code>!htaccess</code> or add them to the existing .htaccess file";
      $replace = array('%directory' => $directory, '!htaccess' => '<br />'. nl2br(check_plain($htaccess_lines)));
      drupal_set_message($message, 'error');
      return FALSE;
    }
  }

  // Check the user agent to make sure we're not responding to a request from drupal itself.
  // That should prevent infinite loops which could be caused by poormanscron in some circumstances.
  if (strpos($_SERVER['HTTP_USER_AGENT'], 'Drupal') !== FALSE) {
    return FALSE;
  }

  // Check to see if the destination is publicly accessible
  $test_contents = "this file should not be publicly accessible";
  // Create the the text.txt file if it's not already there.
  if (!is_file($directory .'/test.txt') || file_get_contents($directory .'/test.txt') != $test_contents) {
    if ($fp = fopen($directory .'/test.txt', 'w')) {
      @fputs($fp, $test_contents);
      fclose($fp);
    }
    else {
      $message = t("Security notice: uc_epay_kkb was unable to write a test text file to the destination directory %directory, and is therefore unable to check the security of it.", array('%directory' => $directory));
      drupal_set_message($message, 'error');
      return FALSE;
    }
  }

  // Attempt to read the test file via http. This may fail for other reasons,
  // so it's not a bullet-proof check.
  $path = trim(drupal_substr($directory .'/test.txt', drupal_strlen(file_directory_path())), '\\/');
  if (uc_epay_kkb_test_file_readable_remotely($path, $test_contents)) {
    $message = t("Security notice: uc_epay_kkb will not save certificate files to the server because the destination directory is publicly accessible. If you want to save files to the server, please secure the '%directory' directory", array('%directory' => $directory));
    drupal_set_message($message, 'error');
    return FALSE;
  }
  return $directory;
}

/**
 * Check if a file can be read remotely via http.
 */
function uc_epay_kkb_test_file_readable_remotely($path, $contents) {
  $url = $GLOBALS['base_url'] .'/'. file_directory_path() .'/'. str_replace('\\', '/', $path);
  $result = drupal_http_request($url);
  if (!empty($result->data) && strpos($result->data, $contents) !== FALSE) {
    return TRUE;
  }
  return FALSE;
}

/**
 * Check certificate files.
 *
 * @return TRUE in certificate files is ok
 */
function uc_epay_kkb_check_cert_files() {
  $result = TRUE;
  if (!file_exists(UC_EPAY_KKB_CERT_DIR . '/' . UC_EPAY_KKB_BANK_CERT_FILENAME)){
    $message = t("uc_epay_kkb was unable to find bank public key %cert. Please, place it in %dir.",
                  array('%cert' => UC_EPAY_KKB_BANK_CERT_FILENAME, '%dir' => UC_EPAY_KKB_CERT_DIR));
    drupal_set_message($message, 'error');
    $result = FALSE;
  }
  if (!file_exists(UC_EPAY_KKB_CERT_DIR . '/' . UC_EPAY_KKB_MERCH_CERT_FILENAME)) {
    $message = t("uc_epay_kkb was unable to find private merchant key %cert. Please, place it in %dir.",
                  array('%cert' => UC_EPAY_KKB_MERCH_CERT_FILENAME, '%dir' => UC_EPAY_KKB_CERT_DIR));
    drupal_set_message($message, 'error');
    $result = FALSE;
  }
  return $result;
}
